# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-04 04:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SltServer', '0003_auto_20180703_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='LotNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='Operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
