# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-04 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SltServer', '0004_auto_20180703_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresultdetail',
            name='Mode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
