# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-05 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SltServer', '0005_auto_20180704_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresultdetail',
            name='TestResult',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Details', to='SltServer.TestResult'),
        ),
    ]
