# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-10 17:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SltServer', '0006_auto_20180705_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='Arch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Arch', to='SltServer.Architecture'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='DutMode',
            field=models.CharField(blank=True, choices=[(b'F', b'fullsgmii'), (b'N', b'nosgmii')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='ExecutionDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='Operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Operator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='SltMode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SltMode', to='SltServer.SltMode'),
        ),
    ]
