# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SltServer', '0009_auto_20180712_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcommand',
            name='FailStop',
            field=models.IntegerField(default=0),
        ),
    ]
