# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 03:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SltServer', '0010_auto_20180726_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bench',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(blank=True, null=True)),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('BoardSerial', models.CharField(blank=True, max_length=255, null=True)),
                ('SocketSerial', models.CharField(blank=True, max_length=255, null=True)),
                ('MacAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('IpAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('Status', models.IntegerField(blank=True, null=True)),
                ('HardwareInfo', models.TextField(blank=True, null=True)),
                ('Architecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Architecture', to='SltServer.Architecture')),
                ('Operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bench',
                'verbose_name_plural': 'Benches',
            },
        ),
    ]
