# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SltServer', '0011_bench'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bench',
            name='Status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
