# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 04:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SltServer', '0012_auto_20180730_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventId', models.IntegerField(blank=True, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Datetime', models.DateTimeField(auto_now_add=True)),
                ('Bench', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bench', to='SltServer.Bench')),
            ],
            options={
                'verbose_name': 'BenchHistory',
                'verbose_name_plural': 'BencheHistories',
            },
        ),
    ]
