# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 04:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SltServer', '0014_auto_20180801_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bench',
            name='Architecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SltServer.Architecture'),
        ),
        migrations.AlterField(
            model_name='bench',
            name='Operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
