# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 04:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SltServer', '0015_auto_20180801_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bench',
            name='Architecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SltServer.Architecture'),
        ),
    ]
