# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SltServer', '0016_auto_20180801_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benchhistory',
            options={'verbose_name': 'BenchHistory', 'verbose_name_plural': 'BenchHistories'},
        ),
    ]
